version: "3"

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image:          australproject/nginx:1.26
    networks:
      - traefik
    restart:        unless-stopped
    depends_on:
      - php
    volumes:
      - "./../:/home/www-data/website"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.permanent=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entryPoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entryPoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.domains[0].main=${DOMAIN}"
    environment:
      TZ:           ${TZ}
      APP_DEBUG:    ${APP_DEBUG}
      APP_ENV:      ${APP_ENV}
      DOMAIN:       ${DOMAIN}
      PUBLIC_DIR:   ${PUBLIC_DIR}
      HTTPS:        ${HTTPS}
    links:
      - php

  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    image: australproject/php:8.2
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - "./../:/home/www-data/website"
      - "./../var/docker-log/php:/var/log"
    environment:
      TZ: ${TZ}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      XDEBUG: ${XDEBUG}
      DOMAIN: ${DOMAIN}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
      PHP_MAX_INPUT_TIME: ${PHP_MAX_INPUT_TIME}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS}

networks:
  traefik:
    external:
      name: traefik
